version: '3'

#     zookeeper:
#         image: confluentinc/cp-zookeeper
#         environment:
#             ZOOKEEPER_CLIENT_PORT: 2181
#             ZOOKEEPER_TICK_TIME: 2000
#         volumes:
#             - zk-data:/var/lib/zookeeper/data
#             - zk-logs:/var/lib/zookeeper/log
#             - secrets:/etc/zookeeper/secrets
#         restart: unless-stopped

#     kafka:
#         image: confluentinc/cp-kafka
#         depends_on:
#             - zookeeper
#         ports: 
#             - "9093:9093"
#         environment:
#             KAFKA_BROKER_ID: 1
#             KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#             KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
#             KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT      
#             KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
#             KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#             KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#         volumes:
#             - kafka-data:/var/lib/kafka/data
#             - secrets:/etc/kafka/secrets
#         restart: unless-stopped

# volumes: 
#     zk-logs: {}
#     zk-data: {}
#     kafka-data: {}
#     secrets: {}

services: 
    # schema lookup table 
    iglu:
        container_name: iglu
        image: nginx
        ports:
            - "81:80"
        volumes:
            - ./iglu:/usr/share/nginx/html:ro
        command: /bin/bash -c "echo 'autoindex on;' > /etc/nginx/conf.d/autoindex.conf && nginx -g 'daemon off;'"
        restart: unless-stopped

    stream-collector:
        container_name: stream-collector 
        image: snowplow-docker-registry.bintray.io/snowplow/scala-stream-collector-kafka:0.14.0
        command: [ "--config", "/snowplow/config/stream-collector.hocon" ]
        # depends_on:
        #     - kafka
        ports:
            - "8080:8080"
        volumes:
            - ./config:/snowplow/config
        environment:
            - "SP_JAVA_OPTS=-Xms512m -Xmx512m"
        extra_hosts: 
            - "host:172.16.33.91"
        restart: unless-stopped

    stream-enrich:
        container_name: stream-enrich
        image: snowplow-docker-registry.bintray.io/snowplow/stream-enrich-kafka:0.19.0
        command: [
            "--config", "/snowplow/config/stream-enrich.hocon",
            "--resolver", "file:/snowplow/config/resolver.json",
            "--enrichments", "file:/snowplow/config/enrichments",
            "--force-cached-files-download"
        ]
        depends_on:
            - stream-collector
        links: 
            - iglu
        volumes:
            - ./config:/snowplow/config
        environment:
            - "SP_JAVA_OPTS=-Xms512m -Xmx512m"
        extra_hosts: 
            - "host:172.16.33.91"
        restart: unless-stopped

    # events-processor:
    #     build: 
    #         context: ./events-processor
    #     extra_hosts: 
    #         - "hd01:10.10.137.41"
    #         - "hd02:10.10.137.42"
    #         - "hd03:10.10.137.43"
    #     restart: unless-stopped
    
    # events-to-es:
    #     build: 
    #         context: ./events-to-es
    #     extra_hosts: 
    #         - "hd01:10.10.137.41"
    #         - "hd02:10.10.137.42"
    #         - "hd03:10.10.137.43"
    #     restart: unless-stopped
        
# volumes: 
#     es-volume:
#     zk-logs: {}
#     zk-data: {}
#     kafka-data: {}
#     secrets: {}