version: '3'

services: 
    # schema lookup table 
    iglu:
        container_name: iglu
        image: nginx
        ports:
            - "81:80"
        volumes:
            - ./iglu:/usr/share/nginx/html:ro
        command: /bin/bash -c "echo 'autoindex on;' > /etc/nginx/conf.d/autoindex.conf && nginx -g 'daemon off;'"
        restart: unless-stopped

    stream-collector:
        container_name: stream-collector 
        image: snowplow-docker-registry.bintray.io/snowplow/scala-stream-collector-kafka:0.14.0
        command: [ "--config", "/snowplow/config/stream-collector.hocon" ]
        # depends_on:
        #     - kafka
        ports:
            - "8080:8080"
        volumes:
            - ./config:/snowplow/config
        environment:
            - "SP_JAVA_OPTS=-Xms512m -Xmx512m"
        extra_hosts: 
            - "host:172.16.33.91"
        restart: unless-stopped

    stream-enrich:
        container_name: stream-enrich
        image: snowplow-docker-registry.bintray.io/snowplow/stream-enrich-kafka:0.19.0
        command: [
            "--config", "/snowplow/config/stream-enrich.hocon",
            "--resolver", "file:/snowplow/config/resolver.json",
            "--enrichments", "file:/snowplow/config/enrichments",
            "--force-cached-files-download"
        ]
        depends_on:
            - stream-collector
        links: 
            - iglu
        volumes:
            - ./config:/snowplow/config
        environment:
            - "SP_JAVA_OPTS=-Xms512m -Xmx512m"
        extra_hosts: 
            - "host:172.16.33.91"
        restart: unless-stopped

    # events-processor:
    #     build: 
    #         context: ./events-processor
    #     extra_hosts: 
    #         - "hd01:10.10.137.41"
    #         - "hd02:10.10.137.42"
    #         - "hd03:10.10.137.43"
    #     restart: unless-stopped
    
    # events-to-es:
    #     build: 
    #         context: ./events-to-es
    #     extra_hosts: 
    #         - "hd01:10.10.137.41"
    #         - "hd02:10.10.137.42"
    #         - "hd03:10.10.137.43"
    #     restart: unless-stopped
        
# volumes: 
#     es-volume:
#     zk-logs: {}
#     zk-data: {}
#     kafka-data: {}
#     secrets: {}